AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - "bin/update"
    - "bin/yarn"
    - "db/schema.rb"

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Layout/LineLength:
  Max: 120

Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/MultilineAssignmentLayout:
  EnforcedStyle: same_line

Layout/CaseIndentation:
  EnforcedStyle: end
